service: 'kickboard-sync'

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-2
  stage: prod
  lambdaHashingVersion: '20201221'

plugins:
  - serverless-webpack

custom:
  webpack:
    includeModules: true

functions:
  app:
    handler: src/index.handler
    events:
      - schedule:
          enabled: true
          rate: cron(0,30 * * * ? *)
