service: 'kickboard-sync'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2
  stage: stage
  timeout: 16

plugins:
  - serverless-webpack
  - serverless-doppler

custom:
  webpack:
    includeModules: true
    packager: 'yarn'
    packagerOptions:
      noFrozenLockfile: true

functions:
  app:
    handler: src/index.handler
    events:
      - schedule:
          enabled: true
          rate: rate(30 minutes)
